# Change these first
owner: gebu8f # Your GitHub organization or username, where this repository lives
repo: UptimeBOT # The name of this repository

sites:
  - name: Passwd
    url: https://passwd.gebu8f.pp.ua
  - name: Alist
    url: https://alist.gebu8f.pp.ua
  - name: Password1
    url: https://pass-4a4m.onrender.com
  - name: Alust1
    url: https://gebu8f-0hnr.onrender.com
  #- name: memos
    #url: https://note.gebu8f.pp.ua
  #- name: memos1
    #url: https://memos-941c.onrender.com
  #- name: Alist123
    #url: http://alist.gebu8f.eu.org
  #- name: Uptime
    #url: https://uptime123.zeabur.app
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.gebu8f.eu.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
